#!/usr/bin/env groovy

node {
    stage 'prepare env'
    env.WORKSPACE = pwd()
    def home = "${env.WORKSPACE}/src/main"
    def mvnHome = tool "M3"

    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean package') {
        sh "${mvnHome}/bin/mvn -s settings.xml clean package docker:build -X -DpushImage -Pdocker-push-develop"
    }

    stage("installing application ") {
        sh """
                ansible-playbook --private-key /etc/ansible/files/developer.pem "${home}/resources/ansible/oms-integration-api-dev-inst.yml"
        """
    }
}